export const AIRPORTS = [
  "GRU – São Paulo (Guarulhos)",
  "CGH – São Paulo (Congonhas)",
  "VCP – Campinas (Viracopos)",
  "GIG – Rio de Janeiro (Galeão)",
  "SDU – Rio de Janeiro (Santos Dumont)",
  "BSB – Brasília",
  "CNF – Belo Horizonte (Confins)",
  "PLU – Belo Horizonte (Pampulha)",
  "SSA – Salvador",
  "FOR – Fortaleza",
  "REC – Recife",
  "MAO – Manaus",
  "BEL – Belém",
  "POA – Porto Alegre",
  "FLN – Florianópolis",
  "CWB – Curitiba",
  "MCZ – Maceió",
  "NAT – Natal",
  "JPA – João Pessoa",
  "THE – Teresina",
  "SLZ – São Luís",
  "CGB – Cuiabá",
  "CGR – Campo Grande",
  "VIX – Vitória",
  "AJU – Aracaju",
  "PMW – Palmas",
  "PVH – Porto Velho",
  "RBR – Rio Branco",
  "MCP – Macapá",
  "BOA – Boa Vista",
  "GYN – Goiânia",
  "IGU – Foz do Iguaçu",
  "LDB – Londrina",
  "MAB – Marabá",
  "IMP – Imperatriz",
  "JOI – Joinville",
  "NVT – Navegantes",
  "UDI – Uberlândia",
  "BVB – Boa Vista",
  "PPB – Presidente Prudente",
  "RAO – Ribeirão Preto",
  "SJK – São José dos Campos",
  "CAC – Cascavel",
  "PFB – Passo Fundo",
  "URG – Uruguaiana",
];
